import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import JSZip from "jszip";

interface ExportButtonProps {
  project: any;
}

const ExportButton = ({ project }: ExportButtonProps) => {
  const { toast } = useToast();

  const handleExport = async () => {
    try {
      const zip = new JSZip();

      // Create index.html with embedded CSS and JS
      const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${project.name}</title>
  <style>${project.css_code}</style>
</head>
<body>
  ${project.html_code}
  <script>${project.js_code}</script>
</body>
</html>`;

      // Also create separate files
      zip.file("index.html", fullHTML);
      zip.file("styles.css", project.css_code);
      zip.file("script.js", project.js_code);
      zip.file("README.md", `# ${project.name}\n\nGenerated by SiteGenie\n\n## Files\n- index.html: Complete website with embedded CSS and JS\n- styles.css: Separate CSS file\n- script.js: Separate JavaScript file`);

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${project.name.replace(/\s+/g, "-").toLowerCase()}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({ title: "Project exported successfully!" });
    } catch (error: any) {
      toast({ 
        title: "Error exporting project", 
        description: error.message,
        variant: "destructive" 
      });
    }
  };

  return (
    <Button variant="outline" size="sm" onClick={handleExport}>
      <Download className="h-4 w-4 mr-2" />
      Export
    </Button>
  );
};

export default ExportButton;
